version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
    user: root
    privileged: true
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/jenkins/config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - npm-network

networks:
  npm-network:
    external: true
    name: npm-network
