# SPRING SETUP
spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            user-info-authentication-method: header
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# SPRINGDOC SETUP
springdoc:
  show-actuator: true

# CUSTOM PROPERTIES
frontend:
  redirect:
    uri: ${FRONTEND_URL}

file:
  path: ${FILE_PATH}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

jwt:
  secret: ${JWT_SECRET}

# imgbb api key
imgbb:
  secret: ${IMGBB_SECRET}
